### ISSUE TITLE
Unable to paste multi-line plaintext from Google Chat to Moped

### ISSUE THREAD

**Issue by perryrivera1** [RobertoMachorro/Moped#34]
Up till yesterday, I was able to paste in multi-line plaintext from Google Chat to Moped. 

As of today, I am no longer able to paste in text from those screens. Everything seems to get placed into one line.

Uninstalling the moped app and reinstalling has had no effect.

I've attached an example. The original source is multiple lines. The paste-up is now only one line.

![Image 8-24-23 at 7 31 AM](https://github.com/RobertoMachorro/Moped/assets/93743187/04217e7a-dde8-4279-8469-96a4d97ec538)

Thanks for taking a look at this..

**Comment by RobertoMachorro** [comment]
Hi @perryrivera1 , it's possible that Google Chat has changed the way they handle new lines. Some applications just do a *carriage return* and consider that a *new line*. In order to further understand the text/content, could you please save a snippet of your text to clipboard, then to a file? You can use the following command line so that all characters are preserved. Attach the file here.

```
$ pbpaste > sample.txt
```

Thanks!

*NOTE:* For your own privacy, only select non-private text, at least two lines.

**Comment by RobertoMachorro** [comment]
No follow up was given, closing issue.
